library(dplyr)
library(tidyr)
library(ggplot2)

setwd("D:\\HSPH\\BIO 260\\final\\data")

basic<-tbl_df(read.csv("Basic.csv",sep="\t"))
brm<-tbl_df(read.csv("blackrock_mountain.csv",sep="\t"))
gng<-tbl_df(read.csv("Goblins_Gnomes.csv",sep="\t"))
classic<-tbl_df(read.csv("Classic.csv",sep="\t"))
naxx<-tbl_df(read.csv("Naxxramas.csv",sep="\t"))
pro<-tbl_df(read.csv("promotion.csv",sep="\t"))
tgt<-tbl_df(read.csv("The_grand_tournament.csv",sep="\t"))
tle<-tbl_df(read.csv("The_league_of_explorers.csv",sep="\t"))


total<-basic%>%select(c(cardId,name,type,cost,attack,health,durability,text,mechanics,playerClass,cardSet,rarity))
classic<-select(classic,c(cardId,name,type,cost,attack,health,durability,text,mechanics,playerClass,cardSet,rarity))
total<-bind_rows(total,classic)
brm<-select(brm,c(cardId,name,type,cost,attack,health,durability,text,mechanics,playerClass,cardSet,rarity))
total<-bind_rows(total,brm)
gng<-select(gng,c(cardId,name,type,cost,attack,health,durability,text,mechanics,playerClass,cardSet,rarity))
total<-bind_rows(total,gng)
naxx<-select(naxx,c(cardId,name,type,cost,attack,health,durability,text,mechanics,playerClass,cardSet,rarity))
pro<-pro%>%mutate(durability=NA,playerClass=NA)%>%select(c(cardId,name,type,cost,attack,health,durability,text,mechanics,playerClass,cardSet,rarity))
tgt<-select(tgt,c(cardId,name,type,cost,attack,health,durability,text,mechanics,playerClass,cardSet,rarity))
tle<-select(tle,c(cardId,name,type,cost,attack,health,durability,text,mechanics,playerClass,cardSet,rarity))
total<-total%>%bind_rows(naxx)
total<-total%>%bind_rows(pro)
total<-total%>%bind_rows(tgt)
total<-total%>%bind_rows(tle)
